nirsunitsrest/nirsUnitsRest/urls.py
from django.conf.urls import url, include
from django.contrib import admin

# from units.views import UnitScheduleViewSet

# from rest_framework import routers
# router = routers.SimpleRouter()
# router.register(r'unit_schedule', UnitScheduleViewSet, base_name='unit_schedule')

urlpatterns = [

	# url(r'^', include(router.urls)),

	url(r'^', include('units.urls', namespace="units")),
    url(r'^admin/', admin.site.urls),
]

nirsunitsrest/units/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include

# REST
from rest_framework.urlpatterns import format_suffix_patterns

from django.views.generic import TemplateView, RedirectView # для разработки
# REST

from .views import (
	home,
	# my_account,
	UnitsListView,
	ScheduleListView,
	UnitScheduleListView,
	MyRecListView,
	# record_add,
	# record_edit,
	# record_print,
	# record_delete,



	# REST
	UnitUserProfileList,
	UnitUserProfileDetail,
	
	# actions with calendar
	schedule_calendar,

	# newREST
	UnitScheduleViewSet,
	)

from rest_framework import routers
router = routers.SimpleRouter()
router.register(r'unit_schedule', UnitScheduleViewSet)

urlpatterns = [

	url(r'^$', RedirectView.as_view(url='units_list/')),
	url(r'^units_list/$', TemplateView.as_view(template_name='units/new_units_list.html'), name='units_list'),
	url(r'^units_list/(?P<unit>.*)/$', schedule_calendar, name='schedule_calendar'),



	# url(r'^record/$', record_add, name='record_add'),
	# url(r'^myaccount/$', my_account, name='my_account'),
	# url(r'^schedule/(?P<pk>\d{1,9})/$', record_edit, name='record_edit'),
	# url(r'^schedule/(?P<pk>\d{1,9})/print/$', record_print, name='record_print'),
	# url(r'^schedule/(?P<pk>\d{1,9})/delete/$', record_delete, name='record_delete'),
	url(r'^schedule/$', ScheduleListView.as_view(), name='schedule_list'),
	url(r'^myrecords/$', MyRecListView.as_view(), name='myrecords_list'),
	url(r'^schedule/(?P<unit>.*)/$', UnitScheduleListView.as_view(), name='unit_schedule_list'),
	# url(r'^record/(?P<unit>.*)/$', record_add, name='record_unit_add'),

]

urlpatterns += router.urls

nirsunitsrest/units/models.py
# -*- coding: utf-8 -*-
from django.core.mail import send_mail
from django.db import models
from django.db.models import Q
from django.db.models.signals import pre_save, post_save, pre_delete, post_delete

from django.contrib.auth.models import User

import datetime

from datetime import timedelta as timedelta_dt
from datetime import time

from django.utils import timezone

# from contracts.models import Contract
# from budget.models import NTGroup

def get_all_users_emails():
    all_testers = UnitUserProfile.objects.filter(notice_me=True)
    email_list = [user.user.email for user in all_testers]
    email_list.sort()
    return email_list


def send_email(my_email, subject):
    send_to = my_email.unit.unit_notice_users_emails()
    send_to.append(my_email.tester.email)
    ntg = my_email.tester.units_profile.ntg
    email_subject = subject + u' %s' % my_email.unit
    email_message = u'''
    
    Испытатель: %s %s
    Установка: %s
    Время начала: %s
    Время окончания: %s
    Группа: %s
    Договор: %s
    Объект: %s
    Примечание: %s

    Система записи на установки
    АО "ЭНПО СПЭЛС"
            ''' % (
        my_email.tester.last_name,
        my_email.tester.first_name,
        my_email.unit,
        my_email.start_work.strftime("%d.%m.%Y %H:%M"),
        my_email.end_work.strftime("%d.%m.%Y %H:%M"),
        ntg.ntg,
        my_email.contract,
        my_email.test_object,
        my_email.note_text,
        )
    send_mail(
        email_subject,
        email_message,
        'units@stoikost.mephi.ru',
        send_to,
        fail_silently=False,
        )


def send_email_to_all(my_email, subject, start_time = None, stop_time = None):
    send_to = get_all_users_emails()
    email_subject = subject
    if start_time and stop_time:
        my_start_time = start_time.strftime("%d.%m.%Y %H:%M")
        my_stop_time = stop_time.strftime("%d.%m.%Y %H:%M")
    else:
        my_start_time = my_email.start_work.strftime("%d.%m.%Y %H:%M")
        my_stop_time = my_email.end_work.strftime("%d.%m.%Y %H:%M")
    email_message = u'''
    
    Освободилось время для работы на установке - %s!!!

    Испытатель: %s %s
    Время начала: %s
    Время окончания: %s

    Система записи на установки
    АО "ЭНПО СПЭЛС"
    
    PS Вы можете отписаться от рассылки по ссылке: http://portal.spels.ru/units/myaccount/
            ''' % (
        my_email.unit,
        my_email.tester.last_name,
        my_email.tester.first_name,
        my_start_time,
        my_stop_time
        )
    send_mail(
        email_subject,
        email_message,
        'units@stoikost.mephi.ru',
        send_to,
        fail_silently=False,
        )


class Unit(models.Model):
    unit_name = models.CharField('Наименование', unique = True, max_length=100)
    unit_manager = models.ForeignKey(User, related_name = 'unit_manager', verbose_name='Начальник установки')
    unit_notice_users = models.ManyToManyField(User, related_name = 'unit_notice', verbose_name='Уведомления', blank = True)
    note_text = models.TextField('Примечания', blank = True, null = True)
    # режим работы
    parallel_records = models.BooleanField(default=False)
    # временной режим работы
    start_work = models.TimeField(verbose_name='Время начала работы установки', default=time(9,0))
    end_work = models.TimeField(verbose_name='Время окончания работы установки', default=time(21,0))
    # длительность записи в днях
    duration_of_record = models.DurationField(verbose_name='Длительность записи', default=timedelta_dt(days=1))


    def unit_notice_users_emails(self):
        email_list = [user.email for user in self.unit_notice_users.all()]
        email_list.append(self.unit_manager.email)
        email_list.sort()
        return email_list

    unit_notice_users_emails.short_description=u'Уведомления'    

    def __str__(self):
        return self.unit_name

    class Meta:
        ordering = ['unit_name']
        verbose_name = u'Установка'
        verbose_name_plural = u'Установки'

def get_busy_dates(unit=None):
    if unit:
        busy_dates_start = UnitSchedule.objects.filter(unit=unit, start_work__date__gte=timezone.now().date()).dates('start_work', 'day')
        busy_dates_end = UnitSchedule.objects.filter(unit=unit, end_work__date__gte=timezone.now().date()).dates('end_work', 'day')
        busy_dates = list(busy_dates_start)
        busy_dates.extend(list(busy_dates_end))
        busy_dates.sort()
    else:
        busy_dates = []
    return busy_dates

def get_free_date(unit=None):
    if unit:
        busy_dates = get_busy_dates(unit)
        start_date = timezone.now().date()
        if start_date.month >= 10:
            end_month = 12
        else:
            end_month = start_date.month + 3
        end_date = datetime.date(start_date.year, end_month, 1)
        day_count = (end_date - start_date).days + 1
        for single_date in [d for d in (start_date + datetime.timedelta(n) for n in range(day_count)) if d <= end_date]:
            if (single_date not in busy_dates) and (single_date.weekday() not in [5,6]):
                return single_date
    return timezone.now()+datetime.timedelta(days=1)


# REST

from django.db import models
from pygments.lexers import get_all_lexers
from pygments.styles import get_all_styles

from pygments.lexers import get_lexer_by_name
from pygments.formatters.html import HtmlFormatter
from pygments import highlight


LEXERS = [item for item in get_all_lexers() if item[1]]
LANGUAGE_CHOICES = sorted([(item[1][0], item[0]) for item in LEXERS])
STYLE_CHOICES = sorted((item, item) for item in get_all_styles())


class UnitSchedule(models.Model):
    unit = models.ForeignKey(Unit, verbose_name = "Установка")
    start_work = models.DateTimeField("Дата и время начала работы")
    end_work = models.DateTimeField("Дата и время окончания работы")
    tester = models.ForeignKey(User, verbose_name="Испытатель")
    # contract = models.ForeignKey(Contract, verbose_name="Договор", on_delete=models.PROTECT)
    test_object = models.CharField("Объект испытаний", max_length = 20)
    DISTANCE_CHOICES = (
        (1, u'малое'),
        (2, u'среднее'),
        (3, u'большое'),
        )
    distance = models.IntegerField("Расстояние", choices = DISTANCE_CHOICES, blank = False, null = True, default=2)
    note_text = models.TextField('Примечания', help_text = u"Укажите режим и требуемые уровни", blank = True, null = True)
    reg_date = models.DateTimeField('Дата регистрации', auto_now_add = True, auto_now = False)
    edit_date = models.DateTimeField('Дата изменений', auto_now_add = False, auto_now = True)
    owner = models.ForeignKey('auth.User', related_name='unit_schedule', on_delete=models.CASCADE)



    def __str__(self):
        return u"%s-%s на %s" % (self.unit, self.tester.last_name, self.start_work.date())

    @property
    def is_past_due(self):
        return timezone.now() > self.end_work

    # небольшое конвертирование полей класса для удобной сериализации
    # можно изменить поля класса на start & end и не использоватать эти две функции
    def get_start_work(self):
        return self.start_work

    def get_end_work(self):
        return self.end_work   

    def get_distance_num(self):
        return self.distance    

    # get value by key 
    def get_distance(self):
        return dict(self.DISTANCE_CHOICES)[self.distance]
        
    def get_tester(self):
        return self.tester 

    def get_tester_id(self):
        return self.tester.id        

    BACKGROUND_COLORS = ['#00ff00', 'yellow', 'red']
    def get_owner_full_name(self):
        full_name = self.owner.first_name + ' ' + self.owner.last_name
        return full_name

    def get_color(self):
        return self.BACKGROUND_COLORS[self.distance - 1]       
            
    class Meta:
        ordering = ['-start_work']
        verbose_name = u'Запись на установку'
        verbose_name_plural = u'Запись на установки'


class UnitUserProfile(models.Model):
    user = models.OneToOneField(User, related_name='units_profile')
    # ntg = models.ForeignKey(NTGroup, verbose_name = "НТГ", related_name = 'ntg_unit')
    tester = models.BooleanField("Испытатель", default=True)
    boss = models.BooleanField("Руководитель НТГ", default=False)
    superboss = models.BooleanField("Начальство", default=False)
    notice_me = models.BooleanField("Получать уведомления", default=False)
    note_text = models.TextField("Примечания", blank = True, null = True)

    def get_fio(self):
        fio = "%s %.1s." % (self.user.last_name, self.user.first_name)
        return fio

    def __str__(self):
        return self.get_fio()

    class Meta:
        ordering = ['user']
        verbose_name = u'Профайл'
        verbose_name_plural = u'Профайлы'

nirsunitsrest/units/templates/units/base-css.html
{% load staticfiles %}

  <!-- <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"> -->
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css"> -->
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css"> -->

  <link rel="stylesheet" 
    href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" 
    integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" 
    crossorigin="anonymous">

  <!-- <link rel="stylesheet" 
    href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css"> -->
  
  <link rel="stylesheet" 
    href="https://use.fontawesome.com/releases/v5.0.13/css/all.css"
    integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp"
    crossorigin="anonymous">

  <!-- FullCalendar -->
  <link rel='stylesheet' href="{% static 'fullcalendar/fullcalendar.min.css'%}"/>
  
  <!-- new timepicker -->
  <link rel="stylesheet" 
    href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/css/tempusdominus-bootstrap-4.min.css" />

  <!-- стили -->
  <link rel='stylesheet' href="{% static 'css/style.css'%}"/>

nirsunitsrest/units/templates/units/base-js.html
{% load staticfiles %}
<!-- FullCalendar -->
<!-- <script src="{% static 'js/moment.min.js' %}"></script> -->

<script src="{% static 'fullcalendar/lib/jquery.min.js' %}"></script>

<script src="{% static 'fullcalendar/lib/moment.min.js'%}"></script>

<script src="{% static 'fullcalendar/fullcalendar.min.js'%}"></script>

<script src="{% static 'fullcalendar/locale-all.js'%}"></script>

<script src="{% static 'js/dist/bundle.js' %}"></script>


<!-- Если подключить jquery из бутстрапа, то перестанет работать календарь, но Toggler-menu заработает(магия) -->

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js"
        integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4"
        crossorigin="anonymous"></script>

    <!-- либа с куками -->
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
    
    
    <!-- new timePicker -->
    <script type="text/javascript" 
    src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha14/js/tempusdominus-bootstrap-4.min.js"></script>

nirsunitsrest/units/templates/units/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link rel="icon" href="{% static 'favicon.ico' %}">
    <title>Запись на установки</title>

<style type="text/css">

  .sub-header {
  text-align: center;
  }

  {% block style %}
  {% endblock %}  

</style>

{% include 'units/base-css.html' %}

  </head>

  <body>

{% include 'units/navbar.html' %}

{% block header %}
{% endblock %}

{% block chart %}
{% endblock %}

{% block content %}
{% endblock %}

{% include 'units/base-js.html' %}

{% block script %}
{% endblock %}

  <footer class="footer">
    <div class="container">
      <p class="text-center text-muted">Пока-что не работает</p>
    </div>
  </footer>

  </body>
</html>

nirsunitsrest/units/templates/units/css.html
{% load staticfiles %}

<!-- Bootstrap core CSS -->
<!-- <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">



  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
 -->

   <link rel='stylesheet' href="{% static 'css/style.css'%}"/>

    <!-- Bootstrap 4 CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">


<!-- <link href="{% static 'css/bootstrap-datetimepicker.min.css' %}" rel="stylesheet"> -->

<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css" rel="stylesheet">


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">


	<link rel='stylesheet' href="{% static 'css/style.css'%}"/>

<!-- FullCalendar -->

  <link rel='stylesheet' href="{% static 'css/jquery-ui.min.css'%}"/>
  
  <link rel='stylesheet' href="{% static 'fullcalendar/fullcalendar.min.css'%}"/>
  
  <!-- Тема Flick -->


  <!-- timepicker -->
  <!-- <link rel='stylesheet' href="{% static 'css/jquery.timepicker.min.css'%}"/> -->

  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">

nirsunitsrest/units/templates/units/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a href="{% url 'units:units_list' %}" class="navbar-brand">
      <img src="https://s3.amazonaws.com/iconbros/icons/icon_pngs/000/000/690/original/pirate-c.png?1512931139" alt="logo" width="40" height="40">
    </a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'units:units_list' %}">Главная <span class="sr-only">(current)</span></a>
      </li>
<!--       <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li> -->
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Установки
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'units:units_list' %}">Все установки</a>
          <div class="dropdown-divider"></div>
          <!-- захардкодено! -->
          <a class="dropdown-item" href="{% url 'units:schedule_calendar' 'АРСА-1' %}">АРСА-1</a>
          <a class="dropdown-item" href="{% url 'units:schedule_calendar' 'АРСА-2' %}">АРСА-2</a>
          <a class="dropdown-item" href="{% url 'units:schedule_calendar' 'Панорама-Cs137' %}">Панорама-Cs137</a>
          <a class="dropdown-item" href="{% url 'units:schedule_calendar' 'Панорама-Co60' %}">Панорама-Co60</a>
          <a class="dropdown-item" href="{% url 'units:schedule_calendar' 'Ускоритель' %}">Ускоритель</a>
          <!-- Взять из sidebar лист этих установок -->

        </div>
      </li>
      <li class="nav-item">
        <span class="navbar-text text-white">
           <!--Сегодня -->{% now "l, d F Y" %} 
        </span>
      </li>
    </ul>

    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <span class="navbar-text text-gray">  Добро пожаловать,</span>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{ request.user.first_name }} {{ request.user.last_name }}!
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Личный кабинет</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Выйти</a>
        </div>
      </li>
    </ul>
    </div>

    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

nirsunitsrest/units/templates/units/new_units_list.html
{% extends "units/base.html" %}
{% load staticfiles %}


{% block content %}
<div class="container" style="margin-top: 10px">
	<div class="row">
		<div class="col-4 ">
			<div class="card" style="width: 18rem;">
			  <img class="card-img-top" src="{% static 'images/panorama137.png'%}" alt="Card image cap">
			  <div class="card-body">
			    <h5 class="card-title">Панорама-Cs137</h5>
			    <p class="card-text">Установка лабораторная опытная «Гамма-Панорама МИФИ» с изотопным источником Cs-137.</p>
			  </div>
			  <div class="dropdown-divider"></div>
			  <div class="card-body">
			    <a href="{% url 'units:schedule_calendar' 'Панорама-Cs137' %}" class="card-link">Записаться на установку</a>
			  </div>
			</div>
		</div>
		<div class="col-4 order-3 ml-auto">
			<div class="card" style="width: 18rem;">
			  <img class="card-img-top" src="{% static 'images/accelerator.png'%}" alt="Card image cap">
			  <div class="card-body">
			    <h5 class="card-title">Ускоритель</h5>
			    <p class="card-text">Импульсные ускорители электронов «АРСА», работающие в режиме генерации электронного или тормозного излучения.</p>
			  </div>
			  <div class="dropdown-divider"></div>
			  <div class="card-body">
			    <a href="{% url 'units:schedule_calendar' 'Ускоритель' %}" class="card-link">Записаться на установку</a>
			  </div>
			</div>
		</div>
		<div class="col-4 order-2">
			<div class="card" style="width: 18rem;">
			  <img class="card-img-top" src="{% static 'images/panorama60.png'%}" alt="Card image cap">
			  <div class="card-body">
			    <h5 class="card-title">Панорама-Co60</h5>
			    <p class="card-text">Установка лабораторная опытная «Гамма-Панорама МИФИ» с изотопными источником Со-60 </p>
			  </div>
			  <div class="dropdown-divider"></div>
			  <div class="card-body">
			    <a href="{% url 'units:schedule_calendar' 'Панорама-Co60' %}" class="card-link">Записаться на установку</a>
			  </div>
			</div>
		</div>
	</div>
	<div class="row" style="margin-top: 10px">
		<div class="col-4 order-1">
			<div class="card" style="width: 18rem;">
			  <img class="card-img-top" src="{% static 'images/arsa.png'%}" alt="Card image cap">
			  <div class="card-body">
			    <h5 class="card-title">АРСА-1</h5>
			    <p class="card-text">Импульсные ускорители электронов «АРСА», работающие в режиме генерации электронного или тормозного излучения.</p>
			  </div>
			  <div class="dropdown-divider"></div>
			  <div class="card-body">
			    <a href="{% url 'units:schedule_calendar' 'АРСА-1' %}" class="card-link">Записаться на установку</a>
			  </div>
			</div>
		</div>
		<div class="col-4 order-3">
			<div class="card" style="width: 18rem;">
			  <img class="card-img-top" src="{% static 'images/arsa2.png'%}" alt="Card image cap">
			  <div class="card-body">
			    <h5 class="card-title">АРСА-2</h5>
			    <p class="card-text">Импульсные ускорители электронов «АРСА», работающие в режиме генерации электронного или тормозного излучения.</p>
			  </div>
			  <div class="dropdown-divider"></div>
			  <div class="card-body">
			    <a href="{% url 'units:schedule_calendar' 'АРСА-2' %}" class="card-link">Записаться на установку</a>
			  </div>
			</div>
		</div>


	</div>
</div>
{% endblock %}

nirsunitsrest/units/templates/units/print.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Запись на установку</title>

<style type="text/css">

table, p {
text-align: left;
font-family: Arial;
font-size: 18pt;
}

</style>


  </head>

  <body>

<p>
Установка:
<br/>
<b>{{ obj.unit }}</b>
</p>

<table width="480 px">
	<tbody>

	<tr>
	<td>
Начало работы:		
	</td>			
	<td>
<b>{{ obj.start_work }}</b>
	</td>			
	</tr>
	<tr>
	<td>
Конец работы:		
	</td>			
	<td>
<b>{{ obj.end_work }}</b>
	</td>			
	</tr>
<tr><td><br/></td><td></td></tr>
	<tr>
	<td>
НТГ:
	</td>			
	<td>
<b>{{ obj.tester.units_profile.ntg.ntg }}</b>
	</td>			
	</tr>
<tr><td><br/></td><td></td></tr>
	<tr>
	<td>
Испытатель:
	</td>			
	<td>
<b>{{ obj.tester }}</b>
	</td>			
	</tr>

</tbody>
</table>

<p>
Договор:
<br/>
<b>{{ obj.contract }}</b>
</p>

<p>
Объект:
<br/>
<b>{{ obj.test_object }}</b>
</p>

<p>
Расстояние: <b>{{ obj.get_distance_display }}</b>
</p>

<p>
Примечание:
<b>{{ obj.note_text|wordwrap:40|linebreaks|truncatechars:120 }}</b>
</p>

</body>
</html>

nirsunitsrest/units/templates/units/sidebar.html
<div class="col-sm-3 col-md-2 sidebar">
  {% if request.user.units_profile.tester %}
  <ul class="nav nav-sidebar">
  <li {% if location == 'units_list' %} class="active" {% endif %}><a href="{% url 'units:units_list' %}">Список установок</a></li>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Расписание <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="{% url 'units:unit_schedule_list' 'АРСА-1' %}">АРСА-1<span class="sr-only"></span></a></li>
          <li><a href="{% url 'units:unit_schedule_list' 'АРСА-2' %}">АРСА-2<span class="sr-only"></span></a></li>
          <li><a href="{% url 'units:unit_schedule_list' 'Панорама-Co60' %}">Панорама-Co60<span class="sr-only"></span></a></li>
          <li><a href="{% url 'units:unit_schedule_list' 'Панорама-Cs137' %}">Панорама-Cs137<span class="sr-only"></span></a></li>
          <li><a href="{% url 'units:unit_schedule_list' 'Ускоритель' %}">Ускоритель<span class="sr-only"></span></a></li>
          <li><a href="{% url 'units:schedule_list' %}">Все установки<span class="sr-only"></span></a></li>
        </ul>
    </li>

  <li {% if location == 'myrecords_list' %} class="active" {% endif %}><a href="{% url 'units:myrecords_list' %}">Мои записи</a></li>
  </ul>
  {% endif %}

  <ul class="nav nav-sidebar">
    <li {% if location == 'my_account' %} class="active" {% endif %}><a href="{% url 'units:my_account' %}">Личный кабинет</a></li>

<!-- вырезал -->

  </ul>
</div>